import { StyleSheet, Platform } from 'react-native';
import { ThemeColors } from '../../styles/themeColors';
import { Spacing } from '../../styles/spacing';
import { Typography } from '../../styles/typography';

export const createStyles = (colors: ThemeColors) =>
  StyleSheet.create({
    container: {
      flex: 1,
      backgroundColor: colors.background,
    },
    headerRightText: {
      fontSize: Typography.fontSize.sm,
      fontWeight: '700',
      color: colors.textPrimary,
      marginRight: Spacing.sm,
    },
    progressBar: {
      width: '100%',
      height: 6,
      backgroundColor: colors.blockBorder,
      marginTop: Spacing.xl,
      overflow: 'hidden',
    },
    progressFillContainer: {
      height: '100%',
      overflow: 'hidden',
    },
    progressFill: {
      width: '100%',
      height: '100%',
    },
    content: {
      flex: 1,
      justifyContent: 'space-between',
    },
    scrollArea: {
      flex: 1,
    },
    scrollContent: {
      flexGrow: 1,
      justifyContent: 'flex-start',
      paddingTop: Spacing.xl,
      paddingBottom: Spacing.sm,
    },
    topSection: {
      flex: 1,
      justifyContent: 'flex-start',
    },
    sentenceCard: {
      marginHorizontal: Spacing.xl,
      backgroundColor: colors.blockBackground,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.blockBorder,
      paddingTop: 16,
      overflow: 'hidden',
    },
    cardHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'space-between',
      paddingHorizontal: 20,
      marginBottom: Spacing.sm,
    },
    sentenceCardLabel: {
      fontSize: 11,
      fontWeight: '800',
      letterSpacing: 1.2,
      textTransform: 'uppercase',
      color: colors.primary,
    },
    cardSettingsButton: {
      width: 28,
      height: 28,
      borderRadius: 14,
      backgroundColor: colors.headerButtonBackground,
      justifyContent: 'center',
      alignItems: 'center',
    },
    sentenceRow: {
      paddingHorizontal: 20,
      flexDirection: 'row',
      flexWrap: 'wrap',
      alignItems: 'center',
      justifyContent: 'flex-start',
      marginTop: Spacing.sm,
      marginBottom: Spacing.xl,
    },
    regularWord: {
      fontSize: 22,
      fontWeight: '600',
      color: colors.textPrimary,
      marginHorizontal: 3,
      marginVertical: 4,
    },
    punctuationText: {
      fontSize: 22,
      fontWeight: '600',
      color: colors.textPrimary,
      marginLeft: -1,
      marginRight: 3,
      marginVertical: 4,
    },
    atomicSlotGroup: {
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
    },
    gapSlot: {
      minWidth: 64,
      height: 38,
      borderRadius: 8,
      marginHorizontal: 3,
      marginVertical: 4,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing.md,
      borderWidth: 1.5,
      borderColor: `${colors.primary}40`,
      backgroundColor: 'transparent',
    },
    gapSlotActive: {
      borderWidth: 2,
      borderColor: colors.primary,
      backgroundColor: `${colors.primary}18`,
    },
    gapSlotFilled: {
      backgroundColor: `${colors.primary}15`,
      borderWidth: 1.5,
      borderColor: colors.primary,
    },
    gapSlotCorrect: {
      backgroundColor: '#10B98122',
      borderWidth: 1.5,
      borderColor: '#10B981',
    },
    gapSlotIncorrect: {
      backgroundColor: '#EF444422',
      borderWidth: 1.5,
      borderColor: '#EF4444',
    },
    gapSlotText: {
      fontSize: 22,
      fontWeight: '700',
      color: colors.primary,
      textAlign: 'center',
      includeFontPadding: false,
    },
    gapSlotTextCorrect: {
      color: '#10B981',
    },
    gapSlotTextIncorrect: {
      color: '#EF4444',
      textDecorationLine: 'line-through',
    },
    sentenceTranslationContainer: {
      borderTopWidth: 1,
      borderTopColor: colors.blockBorder,
      backgroundColor: colors.background,
      borderBottomLeftRadius: 18,
      borderBottomRightRadius: 18,
      paddingHorizontal: 20,
      paddingVertical: 14,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'flex-start',
      gap: 10,
    },
    sentenceTranslationText: {
      flex: 1,
      fontSize: Typography.fontSize.sm,
      color: colors.textSecondary,
      fontStyle: 'italic',
      textAlign: 'left',
      lineHeight: 20,
    },
    bottomSection: {
      paddingHorizontal: Spacing.xl,
    },
    optionsGrid: {
      flexDirection: 'row',
      flexWrap: 'wrap',
      justifyContent: 'space-between',
      rowGap: 12,
    },
    optionButton: {
      width: '48%',
      height: 58,
      borderRadius: 14,
      backgroundColor: colors.blockBackground,
      borderWidth: 1,
      borderColor: colors.blockBorder,
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing.sm,
    },
    optionButtonFullWidth: {
      width: '100%',
    },
    optionButtonSelected: {
      borderColor: colors.primary,
      backgroundColor: `${colors.primary}15`,
    },
    optionButtonCorrect: {
      borderColor: '#10B981',
      backgroundColor: '#10B98125',
    },
    optionButtonIncorrect: {
      borderColor: '#EF4444',
      backgroundColor: '#EF444425',
    },
    optionButtonText: {
      fontSize: Typography.fontSize.md,
      fontWeight: '700',
      color: colors.textPrimary,
      textAlign: 'center',
    },
    optionButtonTextSelected: {
      color: colors.primary,
    },
    optionButtonTextCorrect: {
      color: '#10B981',
    },
    optionButtonTextIncorrect: {
      color: '#EF4444',
    },
    tapToContinueContainer: {
      minHeight: 48,
      flexDirection: 'column',
      justifyContent: 'center',
      alignItems: 'center',
      paddingHorizontal: Spacing.xl,
      paddingTop: 4,
      paddingBottom: Platform.OS === 'ios' ? 4 : 2,
    },
    tapToContinueIcon: {
      marginBottom: Spacing.sm,
      opacity: 0.85,
    },
    tapToContinueText: {
      fontSize: 12,
      fontWeight: '500',
      color: colors.textMuted,
      opacity: 0.85,
      textAlign: 'center',
    },
    correctAnswerCard: {
      marginHorizontal: Spacing.xl,
      marginTop: Spacing.md,
      backgroundColor: colors.blockBackground,
      borderRadius: 18,
      borderWidth: 1,
      borderColor: colors.blockBorder,
      padding: Spacing.xl,
    },
    correctAnswerHeader: {
      flexDirection: 'row',
      alignItems: 'center',
      marginBottom: 6,
    },
    correctAnswerHeaderIcon: {
      marginRight: 6,
    },
    correctAnswerLabel: {
      fontSize: Typography.fontSize.xs,
      fontWeight: '700',
      color: colors.primary,
      textTransform: 'uppercase',
      letterSpacing: 0.8,
    },
    correctAnswerSentenceText: {
      fontSize: 17,
      lineHeight: 26,
      color: colors.textPrimary,
      marginTop: 2,
    },
    correctAnswerWord: {
      fontSize: 17,
      fontWeight: '400',
      color: colors.textPrimary,
    },
    correctAnswerHighlightText: {
      fontSize: 17,
      fontWeight: '700',
      color: '#10B981',
    },
    correctConjugationContainer: {
      flexDirection: 'row',
      marginTop: 4,
    },
    correctConjugationColumn: {
      flex: 1,
      paddingRight: Spacing.xs,
    },
    correctConjugationRow: {
      flexDirection: 'row',
      alignItems: 'center',
      paddingVertical: 2,
    },
    correctConjugationPronoun: {
      fontSize: 15,
      fontWeight: '600',
      color: colors.textSecondary,
      width: 72,
    },
    loadingContainer: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
  });
