export interface ThematicCategory {
  id: string;
  emoji: string;
  iconName: string;
  color: string;
  gradientColors: [string, string];
  titleKey: string;
  subtitleKey: string;
  verbInfinitives: string[];
}

export const THEMATIC_CATEGORIES: ThematicCategory[] = [
  {
    id: 'movement',
    emoji: '🚶',
    iconName: 'walking',
    color: '#3B82F6',
    gradientColors: ['#3B82F6', '#1D4ED8'],
    titleKey: 'categories.movement.title',
    subtitleKey: 'categories.movement.subtitle',
    verbInfinitives: [
      'gehen',
      'fahren',
      'kommen',
      'laufen',
      'fliegen',
      'ankommen',
      'abfahren',
      'umsteigen',
      'aussteigen',
      'mitkommen',
    ],
  },
  {
    id: 'communication',
    emoji: '💬',
    iconName: 'comments',
    color: '#8B5CF6',
    gradientColors: ['#8B5CF6', '#6D28D9'],
    titleKey: 'categories.communication.title',
    subtitleKey: 'categories.communication.subtitle',
    verbInfinitives: [
      'sprechen',
      'sagen',
      'fragen',
      'antworten',
      'erzählen',
      'anrufen',
      'diskutieren',
      'erklären',
    ],
  },
  {
    id: 'home_daily',
    emoji: '🏠',
    iconName: 'home',
    color: '#10B981',
    gradientColors: ['#10B981', '#047857'],
    titleKey: 'categories.homeDaily.title',
    subtitleKey: 'categories.homeDaily.subtitle',
    verbInfinitives: [
      'wohnen',
      'schlafen',
      'aufstehen',
      'aufräumen',
      'putzen',
      'kochen',
      'anziehen',
      'aufmachen',
      'zumachen',
    ],
  },
  {
    id: 'food_drink',
    emoji: '🍕',
    iconName: 'utensils',
    color: '#F59E0B',
    gradientColors: ['#F59E0B', '#B45309'],
    titleKey: 'categories.foodDrink.title',
    subtitleKey: 'categories.foodDrink.subtitle',
    verbInfinitives: [
      'essen',
      'trinken',
      'bestellen',
      'kochen',
      'frühstücken',
      'probieren',
      'schmecken',
    ],
  },
  {
    id: 'work_study',
    emoji: '💼',
    iconName: 'briefcase',
    color: '#6366F1',
    gradientColors: ['#6366F1', '#4338CA'],
    titleKey: 'categories.workStudy.title',
    subtitleKey: 'categories.workStudy.subtitle',
    verbInfinitives: [
      'arbeiten',
      'lernen',
      'studieren',
      'schreiben',
      'lesen',
      'verstehen',
      'wiederholen',
      'organisieren',
    ],
  },
  {
    id: 'shopping_money',
    emoji: '🛒',
    iconName: 'shopping-cart',
    color: '#EC4899',
    gradientColors: ['#EC4899', '#BE185D'],
    titleKey: 'categories.shoppingMoney.title',
    subtitleKey: 'categories.shoppingMoney.subtitle',
    verbInfinitives: [
      'kaufen',
      'verkaufen',
      'bezahlen',
      'kosten',
      'schenken',
      'wechseln',
      'sparen',
    ],
  },
  {
    id: 'thoughts_feelings',
    emoji: '🧠',
    iconName: 'brain',
    color: '#8B5CF6',
    gradientColors: ['#A855F7', '#7E22CE'],
    titleKey: 'categories.thoughtsFeelings.title',
    subtitleKey: 'categories.thoughtsFeelings.subtitle',
    verbInfinitives: [
      'denken',
      'glauben',
      'wissen',
      'freuen',
      'hoffen',
      'fühlen',
      'lieben',
      'vermissen',
    ],
  },
  {
    id: 'leisure_hobbies',
    emoji: '⚽',
    iconName: 'futbol',
    color: '#14B8A6',
    gradientColors: ['#14B8A6', '#0F766E'],
    titleKey: 'categories.leisureHobbies.title',
    subtitleKey: 'categories.leisureHobbies.subtitle',
    verbInfinitives: [
      'spielen',
      'reisen',
      'treffen',
      'schwimmen',
      'wandern',
      'feiern',
      'besichtigen',
    ],
  },
  {
    id: 'health',
    emoji: '🏥',
    iconName: 'heartbeat',
    color: '#EF4444',
    gradientColors: ['#EF4444', '#B91C1C'],
    titleKey: 'categories.health.title',
    subtitleKey: 'categories.health.subtitle',
    verbInfinitives: ['fehlen', 'wehtun', 'fühlen', 'untersuchen', 'husten', 'genesen'],
  },
];
