export interface ThematicCategory {
  id: string;
  emoji: string;
  iconName: string;
  color: string;
  gradientColors: [string, string];
  titleKey: string;
  subtitleKey: string;
  verbInfinitives: string[];
}

export const THEMATIC_CATEGORIES: ThematicCategory[] = [
  {
    id: 'movement',
    emoji: '🚶',
    iconName: 'walking',
    color: '#3B82F6',
    gradientColors: ['#3B82F6', '#1D4ED8'],
    titleKey: 'categories.movement.title',
    subtitleKey: 'categories.movement.subtitle',
    verbInfinitives: [
      'gehen',
      'fahren',
      'kommen',
      'laufen',
      'fliegen',
      'ankommen',
      'abfahren',
      'umsteigen',
      'aussteigen',
      'mitkommen',
      'rennen',
      'springen',
      'eilen',
      'fliehen',
      'spazieren',
      'schleichen',
      'rutschen',
      'schreiten',
      'vorbeigehen',
      'weitergehen',
      'losgehen',
      'zurückkommen',
      'zurückkehren',
      'wandern',
      'steigen',
      'sinken',
      'folgen',
      'verlassen',
      'nähern',
      'bewegen',
      'hinausgehen',
      'aufbrechen',
    ],
  },
  {
    id: 'communication',
    emoji: '💬',
    iconName: 'comments',
    color: '#8B5CF6',
    gradientColors: ['#8B5CF6', '#6D28D9'],
    titleKey: 'categories.communication.title',
    subtitleKey: 'categories.communication.subtitle',
    verbInfinitives: [
      'sprechen',
      'sagen',
      'fragen',
      'antworten',
      'erzählen',
      'anrufen',
      'diskutieren',
      'erklären',
      'berichten',
      'mitteilen',
      'behaupten',
      'widersprechen',
      'begründen',
      'ausdrücken',
      'flüstern',
      'brüllen',
      'schimpfen',
      'kommentieren',
      'vorlesen',
      'vortragen',
      'betonen',
      'wiederholen',
      'bitten',
      'danken',
      'rufen',
      'zugeben',
      'verhandeln',
      'informieren',
      'unterhalten',
      'streiten',
      'loben',
      'kritisieren',
      'befragen',
      'erwähnen',
      'zustimmen',
      'ablehnen',
    ],
  },
  {
    id: 'home_daily',
    emoji: '🏠',
    iconName: 'home',
    color: '#10B981',
    gradientColors: ['#10B981', '#047857'],
    titleKey: 'categories.homeDaily.title',
    subtitleKey: 'categories.homeDaily.subtitle',
    verbInfinitives: [
      'wohnen',
      'schlafen',
      'aufstehen',
      'aufräumen',
      'putzen',
      'kochen',
      'anziehen',
      'aufmachen',
      'zumachen',
      'aufwachen',
      'waschen',
      'ausziehen',
      'öffnen',
      'schließen',
      'abschließen',
      'trocknen',
      'liegen',
      'sitzen',
      'stehen',
      'hängen',
      'bauen',
      'einrichten',
      'einziehen',
      'bleiben',
      'verbringen',
      'legen',
      'stellen',
      'stecken',
      'ordnen',
    ],
  },
  {
    id: 'food_drink',
    emoji: '🍕',
    iconName: 'utensils',
    color: '#F59E0B',
    gradientColors: ['#F59E0B', '#B45309'],
    titleKey: 'categories.foodDrink.title',
    subtitleKey: 'categories.foodDrink.subtitle',
    verbInfinitives: [
      'essen',
      'trinken',
      'bestellen',
      'kochen',
      'frühstücken',
      'probieren',
      'schmecken',
      'backen',
      'braten',
      'schneiden',
      'gießen',
      'fressen',
      'servieren',
      'einnehmen',
      'mischen',
      'genießen',
    ],
  },
  {
    id: 'work_study',
    emoji: '💼',
    iconName: 'briefcase',
    color: '#6366F1',
    gradientColors: ['#6366F1', '#4338CA'],
    titleKey: 'categories.workStudy.title',
    subtitleKey: 'categories.workStudy.subtitle',
    verbInfinitives: [
      'arbeiten',
      'lernen',
      'studieren',
      'schreiben',
      'lesen',
      'verstehen',
      'wiederholen',
      'organisieren',
      'planen',
      'entwickeln',
      'beschäftigen',
      'kündigen',
      'einstellen',
      'bewerben',
      'leiten',
      'führen',
      'prüfen',
      'konzipieren',
      'strukturieren',
      'übernehmen',
      'erledigen',
      'üben',
      'leisten',
      'unterrichten',
      'analysieren',
      'dokumentieren',
      'auswerten',
      'rechnen',
      'erforschen',
      'lösen',
      'beibringen',
      'ausbilden',
    ],
  },
  {
    id: 'shopping_money',
    emoji: '🛒',
    iconName: 'shopping-cart',
    color: '#EC4899',
    gradientColors: ['#EC4899', '#BE185D'],
    titleKey: 'categories.shoppingMoney.title',
    subtitleKey: 'categories.shoppingMoney.subtitle',
    verbInfinitives: [
      'kaufen',
      'verkaufen',
      'bezahlen',
      'kosten',
      'schenken',
      'wechseln',
      'sparen',
      'ausgeben',
      'verdienen',
      'handeln',
      'anbieten',
      'leisten',
      'verdoppeln',
      'abheben',
      'überziehen',
      'bestellen',
      'rechnen',
      'erwerben',
      'stehlen',
      'einnehmen',
      'finanzieren',
      'senken',
      'erhöhen',
      'steigern',
      'verbrauchen',
    ],
  },
  {
    id: 'thoughts_feelings',
    emoji: '🧠',
    iconName: 'brain',
    color: '#A855F7',
    gradientColors: ['#A855F7', '#7E22CE'],
    titleKey: 'categories.thoughtsFeelings.title',
    subtitleKey: 'categories.thoughtsFeelings.subtitle',
    verbInfinitives: [
      'denken',
      'glauben',
      'wissen',
      'freuen',
      'hoffen',
      'fühlen',
      'lieben',
      'vermissen',
      'hassen',
      'fürchten',
      'zweifeln',
      'erinnern',
      'vergessen',
      'wundern',
      'schämen',
      'überlegen',
      'ahnen',
      'nachdenken',
      'entscheiden',
      'bevorzugen',
      'wünschen',
      'spüren',
      'empfinden',
      'leiden',
      'erwarten',
      'bedauern',
      'akzeptieren',
      'begeistern',
      'enttäuschen',
      'verzweifeln',
      'beruhigen',
    ],
  },
  {
    id: 'leisure_hobbies',
    emoji: '⚽',
    iconName: 'futbol',
    color: '#14B8A6',
    gradientColors: ['#14B8A6', '#0F766E'],
    titleKey: 'categories.leisureHobbies.title',
    subtitleKey: 'categories.leisureHobbies.subtitle',
    verbInfinitives: [
      'spielen',
      'reisen',
      'treffen',
      'schwimmen',
      'wandern',
      'feiern',
      'besichtigen',
      'tanzen',
      'singen',
      'malen',
      'zeichnen',
      'fotografieren',
      'segeln',
      'klettern',
      'tauchen',
      'gewinnen',
      'verlieren',
      'trainieren',
      'reiten',
      'lauschen',
      'spazieren',
      'unternehmen',
      'zuhören',
      'entspannen',
      'genießen',
      'erholen',
    ],
  },
  {
    id: 'health',
    emoji: '🏥',
    iconName: 'heartbeat',
    color: '#EF4444',
    gradientColors: ['#EF4444', '#B91C1C'],
    titleKey: 'categories.health.title',
    subtitleKey: 'categories.health.subtitle',
    verbInfinitives: [
      'fehlen',
      'wehtun',
      'fühlen',
      'untersuchen',
      'husten',
      'genesen',
      'leiden',
      'erleiden',
      'operieren',
      'pflegen',
      'behandeln',
      'atmen',
      'erholen',
      'vorbeugen',
      'überleben',
      'sterben',
      'versterben',
      'verletzen',
      'überstehen',
      'stärken',
    ],
  },
  {
    id: 'nature_environment',
    emoji: '🌳',
    iconName: 'tree',
    color: '#16A34A',
    gradientColors: ['#16A34A', '#15803D'],
    titleKey: 'categories.natureEnvironment.title',
    subtitleKey: 'categories.natureEnvironment.subtitle',
    verbInfinitives: [
      'regnen',
      'scheinen',
      'wehen',
      'blühen',
      'wachsen',
      'rauschen',
      'leuchten',
      'fließen',
      'brennen',
      'untergehen',
      'aufgehen',
      'trocknen',
      'schützen',
      'zerstören',
      'entstehen',
      'verändern',
    ],
  },
  {
    id: 'law_society',
    emoji: '⚖️',
    iconName: 'balance-scale',
    color: '#0284C7',
    gradientColors: ['#0284C7', '#0369A1'],
    titleKey: 'categories.lawSociety.title',
    subtitleKey: 'categories.lawSociety.subtitle',
    verbInfinitives: [
      'wählen',
      'regieren',
      'entscheiden',
      'verbieten',
      'erlauben',
      'verteidigen',
      'verhaften',
      'festnehmen',
      'vernehmen',
      'erlassen',
      'protestieren',
      'repräsentieren',
      'klagen',
      'überwachen',
      'dulden',
      'kontrollieren',
      'abstimmen',
      'verurteilen',
      'berechtigen',
      'rechtfertigen',
      'beurteilen',
      'bestätigen',
      'gestatten',
    ],
  },
  {
    id: 'relations_social',
    emoji: '🤝',
    iconName: 'hands-helping',
    color: '#F97316',
    gradientColors: ['#F97316', '#C2410C'],
    titleKey: 'categories.relationsSocial.title',
    subtitleKey: 'categories.relationsSocial.subtitle',
    verbInfinitives: [
      'helfen',
      'vertrauen',
      'unterstützen',
      'versprechen',
      'enttäuschen',
      'streiten',
      'umarmen',
      'begrüßen',
      'verabschieden',
      'einladen',
      'anvertrauen',
      'loben',
      'begegnen',
      'begleiten',
      'zuhören',
      'trösten',
      'schätzen',
      'lieben',
      'achten',
      'kennen',
      'treffen',
      'einigen',
      'danken',
    ],
  },
  {
    id: 'creation_change',
    emoji: '🔄',
    iconName: 'sync-alt',
    color: '#0D9488',
    gradientColors: ['#0D9488', '#0F766E'],
    titleKey: 'categories.creationChange.title',
    subtitleKey: 'categories.creationChange.subtitle',
    verbInfinitives: [
      'schaffen',
      'verändern',
      'ändern',
      'zerstören',
      'umwandeln',
      'entstehen',
      'verschwinden',
      'vermindern',
      'verstärken',
      'verschärfen',
      'vereinfachen',
      'bilden',
      'erzeugen',
      'herstellen',
      'formen',
      'verbessern',
      'ersetzen',
      'anpassen',
      'wandeln',
      'gestalten',
      'entwickeln',
      'aufbauen',
      'reduzieren',
      'erweitern',
      'verdoppeln',
    ],
  },
  {
    id: 'travel_transport',
    emoji: '✈️',
    iconName: 'plane',
    color: '#0EA5E9',
    gradientColors: ['#0EA5E9', '#0284C7'],
    titleKey: 'categories.travelTransport.title',
    subtitleKey: 'categories.travelTransport.subtitle',
    verbInfinitives: [
      'reisen',
      'fahren',
      'fliegen',
      'ankommen',
      'abfahren',
      'einsteigen',
      'aussteigen',
      'umsteigen',
      'packen',
      'bremsen',
      'überholen',
      'steuern',
      'starten',
      'transportieren',
      'liefern',
      'landen',
      'anhalten',
      'verkehren',
      'besichtigen',
    ],
  },
  {
    id: 'perception_senses',
    emoji: '👁️',
    iconName: 'eye',
    color: '#64748B',
    gradientColors: ['#64748B', '#334155'],
    titleKey: 'categories.perceptionSenses.title',
    subtitleKey: 'categories.perceptionSenses.subtitle',
    verbInfinitives: [
      'sehen',
      'hören',
      'riechen',
      'schmecken',
      'fühlen',
      'bemerken',
      'beobachten',
      'lauschen',
      'erkennen',
      'überwachen',
      'reflektieren',
      'spiegeln',
      'ansehen',
      'zuhören',
      'betrachten',
      'wahrnehmen',
      'blicken',
      'schauen',
      'entdecken',
      'übersehen',
      'prüfen',
      'merken',
    ],
  },
  {
    id: 'digital_media',
    emoji: '💻',
    iconName: 'laptop',
    color: '#4F46E5',
    gradientColors: ['#4F46E5', '#3730A3'],
    titleKey: 'categories.digitalMedia.title',
    subtitleKey: 'categories.digitalMedia.subtitle',
    verbInfinitives: [
      'installieren',
      'speichern',
      'löschen',
      'senden',
      'empfangen',
      'übertragen',
      'starten',
      'bedienen',
      'anschließen',
      'ausschalten',
      'einschalten',
      'funktionieren',
      'einbauen',
      'abschalten',
      'fotografieren',
      'anwenden',
    ],
  },
];
