import { StyleSheet } from 'react-native';
import { ThemeColors } from '../../styles/themeColors';
import { Spacing, BorderRadius } from '../../styles/spacing';
import { Typography } from '../../styles/typography';

export const createStyles = (colors: ThemeColors, isDark: boolean) =>
  StyleSheet.create({
    overlay: {
      flex: 1,
      justifyContent: 'center',
      alignItems: 'center',
    },
    backdrop: {
      ...StyleSheet.absoluteFillObject,
      backgroundColor: 'rgba(0, 0, 0, 0.65)',
    },
    modalContainer: {
      width: '86%',
      maxWidth: 380,
      backgroundColor: colors.blockBackground,
      borderRadius: BorderRadius.xl,
      overflow: 'hidden',
      borderWidth: 1,
      borderColor: colors.blockBorder,
      elevation: 10,
      shadowColor: '#000',
      shadowOffset: { width: 0, height: 10 },
      shadowOpacity: 0.25,
      shadowRadius: 20,
    },
    gradient: {
      padding: Spacing.xl,
    },
    closeButton: {
      position: 'absolute',
      top: Spacing.md,
      right: Spacing.md,
      width: 32,
      height: 32,
      borderRadius: 16,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.08)' : 'rgba(0, 0, 0, 0.06)',
      justifyContent: 'center',
      alignItems: 'center',
      zIndex: 10,
    },
    content: {
      alignItems: 'center',
      marginTop: Spacing.lg,
    },
    iconCircle: {
      width: 64,
      height: 64,
      borderRadius: 32,
      backgroundColor: `${colors.primary}20`,
      justifyContent: 'center',
      alignItems: 'center',
      marginBottom: Spacing.md,
    },
    title: {
      fontSize: 22,
      fontWeight: '800',
      color: colors.textPrimary,
      textAlign: 'center',
      marginBottom: Spacing.xs,
    },
    message: {
      fontSize: Typography.fontSize.sm,
      color: colors.textSecondary,
      textAlign: 'center',
      lineHeight: 20,
      marginBottom: Spacing.xl,
      paddingHorizontal: Spacing.xs,
    },
    premiumButton: {
      width: '100%',
      backgroundColor: colors.primary,
      paddingVertical: 14,
      paddingHorizontal: Spacing.md,
      borderRadius: BorderRadius.lg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
      shadowColor: colors.primary,
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.3,
      shadowRadius: 8,
      elevation: 4,
    },
    premiumButtonIcon: {
      width: 24,
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    premiumButtonText: {
      flex: 1,
      color: '#FFFFFF',
      fontSize: Typography.fontSize.md,
      fontWeight: '700',
      textAlign: 'center',
    },
    premiumButtonSubtitle: {
      fontSize: Typography.fontSize.xs,
      color: colors.textSecondary,
      textAlign: 'center',
      marginTop: Spacing.xs,
      marginBottom: Spacing.xs,
    },
    divider: {
      width: '100%',
      flexDirection: 'row',
      alignItems: 'center',
      marginVertical: Spacing.md,
    },
    dividerLine: {
      flex: 1,
      height: 1,
      backgroundColor: isDark ? 'rgba(255, 255, 255, 0.12)' : 'rgba(0, 0, 0, 0.1)',
    },
    dividerText: {
      marginHorizontal: Spacing.sm,
      fontSize: Typography.fontSize.xs,
      color: colors.textMuted,
      textTransform: 'uppercase',
      fontWeight: '600',
    },
    retryButton: {
      width: '100%',
      backgroundColor: 'transparent',
      borderWidth: 1.5,
      borderColor: colors.primary,
      paddingVertical: 14,
      paddingHorizontal: Spacing.md,
      borderRadius: BorderRadius.lg,
      flexDirection: 'row',
      alignItems: 'center',
      justifyContent: 'center',
    },
    retryButtonIcon: {
      width: 24,
      alignItems: 'flex-start',
      justifyContent: 'center',
    },
    retryButtonText: {
      flex: 1,
      color: colors.primary,
      fontSize: Typography.fontSize.md,
      fontWeight: '700',
      textAlign: 'center',
    },
  });
